<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <description>The 'Learn Java Logging' Course: Logback</description>
    <name>logback</name>

    <groupId>com.baeldung</groupId>
    <artifactId>ljl-logback</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>getting-started-with-logback-start</module>
        <module>getting-started-with-logback-end</module>
        <module>logback-configuration-start</module>
        <module>logback-configuration-end</module>
        <module>advanced-logback-features-start</module>
        <module>advanced-logback-features-end</module>
    </modules>
</project>